// GENERATED by tools/gen_mesh_fixtures.py — do not edit.
//
// Bytes encoded by Meshtastic's own protobuf library, so the decoder is
// tested against the real schema rather than against our reading of it.

/// FromRadio{ node_info } for node !7c3f0a1b at Mt Hood.
pub const FROM_RADIO_NODE_INFO: &str = "2256089b94fce107121d0a09213763336630613162120b446164277320747275636b1a034441441a1a0d40760b1b1500aa76b7189f0e25204f5d6a7804980109b80120250000c8402d254f5d6a3207085415f6287c404802";

/// FromRadio{ packet } carrying a POSITION_APP payload.
pub const FROM_RADIO_POSITION: &str = "123b0d1b0a3f7c15ffffffff221e0803121a0d40760b1b1500aa76b7189f0e25204f5d6a7804980109b8012035cdab34123d3e4f5d6a45000020c04803";

/// The same, but deliberately fuzzed to 16 bits of precision.
pub const FROM_RADIO_FUZZED: &str = "122a0dc922ba51221e0803121a0d40760b1b1500aa76b7189f0e25204f5d6a7804980109b801103d204f5d6a";

/// A TEXT_MESSAGE_APP packet — must be skipped, not misread.
pub const FROM_RADIO_TEXT: &str = "12140d1b0a3f7c220d080112096f6e206d7920776179";

/// FromRadio{ config_complete_id } — the end of the initial sync.
pub const FROM_RADIO_CONFIG_COMPLETE: &str = "38effdb6f50d";

/// ToRadio{ want_config_id: 0xDEADBEEF } — what we must send on connect.
pub const TO_RADIO_WANT_CONFIG: &str = "18effdb6f50d";

/// ToRadio{ heartbeat }.
pub const TO_RADIO_HEARTBEAT: &str = "3a00";

/// Debug chatter followed by three framed messages.
pub const STREAM_WITH_NOISE: &str = "494e464f207c203f3f3a3f3f3a3f3f2031205b526f757465725d20726164696f206f6b0d0a94c300582256089b94fce107121d0a09213763336630613162120b446164277320747275636b1a034441441a1a0d40760b1b1500aa76b7189f0e25204f5d6a7804980109b80120250000c8402d254f5d6a3207085415f6287c40480294c3003d123b0d1b0a3f7c15ffffffff221e0803121a0d40760b1b1500aa76b7189f0e25204f5d6a7804980109b8012035cdab34123d3e4f5d6a45000020c0480394c3000638effdb6f50d";

// Values the fixtures above encode, for the assertions.
pub const NODE_NUM: u32 = 0x7c3f0a1b;
pub const LAT_I: i32 = 453736000;
pub const LON_I: i32 = -1216960000;
pub const FIX_TIME: u32 = 1784500000;
