#!/usr/bin/env python3
"""Generate golden Meshtastic protobuf fixtures for the Rust decoder's tests.

The decoder in src-tauri/src/mesh.rs reads Meshtastic's wire format by hand
rather than pulling in prost and eight vendored .proto files. That is a small,
dependency-free decoder — but only if it is right, and a protobuf field number
read wrong does not fail loudly: it silently decodes a teammate's position to
the wrong place, which on a map people navigate by is the worst failure
available.

So the tests do not check the decoder against our own idea of the format. They
check it against bytes encoded by Meshtastic's own published protobuf library,
which is the actual schema the radios use. This script produces those bytes.

    pip install meshtastic
    python3 tools/gen_mesh_fixtures.py

Re-run when the schema changes; commit the output so tests need no network.
"""

import sys

try:
    from meshtastic.protobuf import mesh_pb2, portnums_pb2, telemetry_pb2
except ImportError:
    sys.exit("pip install meshtastic first")

OUT = "src-tauri/src/mesh_fixtures.rs"

# A position with the kind of values a real node reports: Mt Hood, a fix a
# couple of minutes old, moving, and reporting its altitude.
LAT, LON = 45.3736, -121.6960
NODE_NUM = 0x7C3F0A1B
FIX_TIME = 1_784_500_000


def position():
    p = mesh_pb2.Position()
    p.latitude_i = int(round(LAT * 1e7))
    p.longitude_i = int(round(LON * 1e7))
    p.altitude = 1823
    p.time = FIX_TIME
    p.ground_speed = 4
    p.sats_in_view = 9
    p.precision_bits = 32
    return p


def node_info():
    n = mesh_pb2.NodeInfo()
    n.num = NODE_NUM
    n.user.id = "!7c3f0a1b"
    n.user.long_name = "Dad's truck"
    n.user.short_name = "DAD"
    n.position.CopyFrom(position())
    n.snr = 6.25
    n.last_heard = FIX_TIME + 5
    n.hops_away = 2
    m = telemetry_pb2.DeviceMetrics()
    m.battery_level = 84
    m.voltage = 3.94
    n.device_metrics.CopyFrom(m)
    return n


def from_radio_node_info():
    f = mesh_pb2.FromRadio()
    f.node_info.CopyFrom(node_info())
    return f


def from_radio_position_packet():
    """A live POSITION_APP packet — the other way a position arrives."""
    f = mesh_pb2.FromRadio()
    pkt = f.packet
    pkt.__setattr__("from", NODE_NUM)
    pkt.to = 0xFFFFFFFF
    pkt.id = 0x1234ABCD
    pkt.rx_time = FIX_TIME + 30
    pkt.rx_snr = -2.5
    pkt.hop_limit = 3
    pkt.decoded.portnum = portnums_pb2.PortNum.POSITION_APP
    pkt.decoded.payload = position().SerializeToString()
    return f


def from_radio_fuzzed_position():
    """precision_bits below 32 means the position is deliberately fuzzed."""
    f = mesh_pb2.FromRadio()
    pkt = f.packet
    pkt.__setattr__("from", 0x51BA22C9)
    pkt.rx_time = FIX_TIME
    pkt.decoded.portnum = portnums_pb2.PortNum.POSITION_APP
    p = position()
    p.precision_bits = 16
    pkt.decoded.payload = p.SerializeToString()
    return f


def from_radio_text_packet():
    """A packet we don't care about — the decoder must skip it, not choke."""
    f = mesh_pb2.FromRadio()
    pkt = f.packet
    pkt.__setattr__("from", NODE_NUM)
    pkt.decoded.portnum = portnums_pb2.PortNum.TEXT_MESSAGE_APP
    pkt.decoded.payload = b"on my way"
    return f


def from_radio_config_complete():
    f = mesh_pb2.FromRadio()
    f.config_complete_id = 0xDEADBEEF
    return f


def to_radio_want_config():
    t = mesh_pb2.ToRadio()
    t.want_config_id = 0xDEADBEEF
    return t


def to_radio_heartbeat():
    t = mesh_pb2.ToRadio()
    t.heartbeat.SetInParent()
    return t


def frame(payload: bytes) -> bytes:
    """The Stream API framing: 0x94 0xC3 then a big-endian uint16 length."""
    return b"\x94\xc3" + len(payload).to_bytes(2, "big") + payload


def hexlit(b: bytes) -> str:
    return '"' + "".join(f"{x:02x}" for x in b) + '"'


def main():
    ni = from_radio_node_info().SerializeToString()
    pos = from_radio_position_packet().SerializeToString()
    fuzzed = from_radio_fuzzed_position().SerializeToString()
    text = from_radio_text_packet().SerializeToString()
    done = from_radio_config_complete().SerializeToString()
    want = to_radio_want_config().SerializeToString()
    beat = to_radio_heartbeat().SerializeToString()

    # A realistic stream: device debug chatter, then frames back to back, with
    # a frame split so the reader has to buffer across reads.
    stream = b"INFO | ??:??:?? 1 [Router] radio ok\r\n" + frame(ni) + frame(pos) + frame(done)

    lines = [
        "// GENERATED by tools/gen_mesh_fixtures.py — do not edit.",
        "//",
        "// Bytes encoded by Meshtastic's own protobuf library, so the decoder is",
        "// tested against the real schema rather than against our reading of it.",
        "",
        f"/// FromRadio{{ node_info }} for node !{NODE_NUM:08x} at Mt Hood.",
        f"pub const FROM_RADIO_NODE_INFO: &str = {hexlit(ni)};",
        "",
        "/// FromRadio{ packet } carrying a POSITION_APP payload.",
        f"pub const FROM_RADIO_POSITION: &str = {hexlit(pos)};",
        "",
        "/// The same, but deliberately fuzzed to 16 bits of precision.",
        f"pub const FROM_RADIO_FUZZED: &str = {hexlit(fuzzed)};",
        "",
        "/// A TEXT_MESSAGE_APP packet — must be skipped, not misread.",
        f"pub const FROM_RADIO_TEXT: &str = {hexlit(text)};",
        "",
        "/// FromRadio{ config_complete_id } — the end of the initial sync.",
        f"pub const FROM_RADIO_CONFIG_COMPLETE: &str = {hexlit(done)};",
        "",
        "/// ToRadio{ want_config_id: 0xDEADBEEF } — what we must send on connect.",
        f"pub const TO_RADIO_WANT_CONFIG: &str = {hexlit(want)};",
        "",
        "/// ToRadio{ heartbeat }.",
        f"pub const TO_RADIO_HEARTBEAT: &str = {hexlit(beat)};",
        "",
        "/// Debug chatter followed by three framed messages.",
        f"pub const STREAM_WITH_NOISE: &str = {hexlit(stream)};",
        "",
        "// Values the fixtures above encode, for the assertions.",
        f"pub const NODE_NUM: u32 = 0x{NODE_NUM:08x};",
        f"pub const LAT_I: i32 = {int(round(LAT * 1e7))};",
        f"pub const LON_I: i32 = {int(round(LON * 1e7))};",
        f"pub const FIX_TIME: u32 = {FIX_TIME};",
        "",
    ]
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines))
    print(f"wrote {OUT}")
    print(f"  node_info {len(ni)} B, position {len(pos)} B, stream {len(stream)} B")


if __name__ == "__main__":
    main()
