// Turn NOAA's WMM.COF into src/wmm2025.ts.
//
// The coefficients are transcribed by machine on purpose: a single mistyped
// digit is a silently wrong declination, which is exactly the error a compass
// correction is supposed to remove. Re-run when the model is replaced (WMM is
// reissued every five years; WMM2025 expires 2030.0).
//
//   node tools/gen_wmm.mjs path/to/WMM.COF
//
// Source: https://www.ncei.noaa.gov/products/world-magnetic-model/wmm-coefficients

import { readFileSync, writeFileSync } from "fs";

const cof = process.argv[2];
if (!cof) {
  console.error("usage: node tools/gen_wmm.mjs <WMM.COF>");
  process.exit(1);
}

const lines = readFileSync(cof, "utf8").split("\n");
const header = lines[0].trim().split(/\s+/);
const epoch = Number(header[0]);
const model = header[1];
if (!Number.isFinite(epoch)) throw new Error(`bad epoch line: ${lines[0]}`);

const rows = [];
for (const raw of lines.slice(1)) {
  const line = raw.trim();
  if (!line || line.startsWith("9999")) continue;
  const [n, m, g, h, gd, hd] = line.split(/\s+/).map(Number);
  if (![n, m, g, h, gd, hd].every(Number.isFinite))
    throw new Error(`bad coefficient line: ${raw}`);
  rows.push({ n, m, g, h, gd, hd });
}

const maxN = Math.max(...rows.map((r) => r.n));
const expected = (maxN * (maxN + 3)) / 2;
if (rows.length !== expected)
  throw new Error(`expected ${expected} coefficients for degree ${maxN}, got ${rows.length}`);

// Flat arrays indexed by n*(n+1)/2+m — the shape geomag.ts sums over.
const size = ((maxN + 1) * (maxN + 2)) / 2;
const g = new Array(size).fill(0);
const h = new Array(size).fill(0);
const gd = new Array(size).fill(0);
const hd = new Array(size).fill(0);
for (const r of rows) {
  const i = (r.n * (r.n + 1)) / 2 + r.m;
  g[i] = r.g;
  h[i] = r.h;
  gd[i] = r.gd;
  hd[i] = r.hd;
}

const fmt = (a) => `[${a.map((v) => String(v)).join(", ")}]`;

writeFileSync(
  new URL("../src/wmm2025.ts", import.meta.url),
  `// GENERATED by tools/gen_wmm.mjs from NOAA's ${model} WMM.COF — do not edit.
//
// World Magnetic Model ${model}, epoch ${epoch.toFixed(1)}, valid to ${(epoch + 5).toFixed(1)}.
// Public domain (US Government work). Main-field coefficients in nT and their
// secular variation in nT/year, flattened to index n*(n+1)/2+m.

export const WMM_EPOCH = ${epoch};
export const WMM_MODEL = ${JSON.stringify(model)};
export const WMM_MAX_N = ${maxN};

export const WMM_G: readonly number[] = ${fmt(g)};

export const WMM_H: readonly number[] = ${fmt(h)};

export const WMM_GDOT: readonly number[] = ${fmt(gd)};

export const WMM_HDOT: readonly number[] = ${fmt(hd)};
`
);

console.log(`wrote src/wmm2025.ts — ${model}, epoch ${epoch}, degree ${maxN}, ${rows.length} coefficients`);
