import { invoke } from "@tauri-apps/api/core";
import { isPlan, type Plan } from "./plan";
import { isKit, type Kit } from "./kit";
import { isComms, isPerson, type CommsPlan, type Person } from "./roster";
import { isId, isLatLng, isOptStr, isStr } from "./valid";

// Durable storage for the user's own data — waypoints, recorded tracks, and the
// bug-out plans made before any of this was needed.
//
// These are the only things in the app that can't be regenerated: a map pack can
// be re-downloaded, a pin you dropped in the field can't. They used to live in
// localStorage, which in a Tauri app is a webview cache directory that a
// reinstall or webview update can silently wipe. They now live in marks.json in
// the app data dir, written atomically on the Rust side.
//
// localStorage is still the fallback when there's no Tauri backend (plain
// `vite dev` in a browser), and is read once to migrate existing data over.

export interface Waypoint {
  id: string;
  name: string;
  lat: number;
  lng: number;
  note?: string;
  t: number;
}
export type Pt = [number, number, number?]; // lng, lat, ele?
export interface Track {
  id: string;
  name: string;
  pts: Pt[];
  t: number;
}
export interface Marks {
  waypoints: Waypoint[];
  tracks: Track[];
  /** Bug-out plans — routes frozen while there was still data. See plan.ts. */
  plans: Plan[];
  /** Kit checklists, with what you have and when it lapses. See kit.ts. */
  kits: Kit[];
  /** Who is in the group, and their medical facts. See roster.ts. */
  roster: Person[];
  /** How you raise each other when the phones stop. Null until written. */
  comms: CommsPlan | null;
}

const WP_KEY = "griddown_waypoints";
const TR_KEY = "griddown_tracks";
const PLAN_KEY = "griddown_plans";
const KIT_KEY = "griddown_kits";
const ROSTER_KEY = "griddown_roster";
const COMMS_KEY = "griddown_comms";

const empty = (): Marks => ({
  waypoints: [],
  tracks: [],
  plans: [],
  kits: [],
  roster: [],
  comms: null,
});

/** Does this hold any user data at all? Only used to decide whether a stored
 *  file is genuinely empty — see the migration in loadMarks, which must not
 *  mistake "plans but no pins" for "nothing here". */
function isEmpty(m: Marks): boolean {
  return (
    !m.waypoints.length &&
    !m.tracks.length &&
    !m.plans.length &&
    !m.kits.length &&
    !m.roster.length &&
    !m.comms
  );
}

function hasTauri(): boolean {
  return typeof (window as any).__TAURI_INTERNALS__ !== "undefined";
}

function readLocalStorage(): Marks {
  const parse = <T>(key: string): T[] => {
    try {
      const v = JSON.parse(localStorage.getItem(key) || "[]");
      return Array.isArray(v) ? v : [];
    } catch {
      return [];
    }
  };
  let comms: CommsPlan | null = null;
  try {
    const raw = localStorage.getItem(COMMS_KEY);
    const v = raw ? JSON.parse(raw) : null;
    comms = isComms(v) ? v : null;
  } catch {
    comms = null;
  }
  return {
    waypoints: parse<Waypoint>(WP_KEY),
    tracks: parse<Track>(TR_KEY),
    plans: parse<Plan>(PLAN_KEY),
    kits: parse<Kit>(KIT_KEY),
    roster: parse<Person>(ROSTER_KEY),
    comms,
  };
}

function writeLocalStorage(m: Marks) {
  try {
    localStorage.setItem(WP_KEY, JSON.stringify(m.waypoints));
    localStorage.setItem(TR_KEY, JSON.stringify(m.tracks));
    localStorage.setItem(PLAN_KEY, JSON.stringify(m.plans));
    localStorage.setItem(KIT_KEY, JSON.stringify(m.kits));
    localStorage.setItem(ROSTER_KEY, JSON.stringify(m.roster));
    localStorage.setItem(COMMS_KEY, JSON.stringify(m.comms));
  } catch {
    /* quota or disabled storage — the file is the real store anyway */
  }
}

/** Coerce anything we read back into a well-formed Marks. */
export function normalize(v: any): Marks {
  const m = empty();
  if (v && typeof v === "object") {
    if (Array.isArray(v.waypoints)) m.waypoints = v.waypoints.filter(isWaypoint);
    if (Array.isArray(v.tracks)) m.tracks = v.tracks.filter(isTrack);
    if (Array.isArray(v.plans)) m.plans = v.plans.filter(isPlan);
    if (Array.isArray(v.kits)) m.kits = v.kits.filter(isKit);
    if (Array.isArray(v.roster)) m.roster = v.roster.filter(isPerson);
    // All or nothing. Half a comms plan is worse than none: it looks filled in,
    // so nobody fills it in.
    if (isComms(v.comms)) m.comms = v.comms;
  }
  return m;
}

// Ids are generated by us (rid()), but they also arrive from restored backups
// and GPX imports, which are attacker-supplied files. ID_RE and the rest of the
// shared guards live in valid.ts, because plans, kits and the roster all read
// back out of this same file and needed the same rules.
//
// Types are checked as well as ids. A restored backup is a file someone else
// may have written, and the renderers assume these are strings and numbers —
// a numeric `name` reaches `.replace()` and throws, which takes out the Marks
// panel entirely, and a malformed `pts` produces NaN coordinates that make
// fitBounds throw. Rejecting the entry is better than a panel that won't open.
// The bar is not "does it parse". It is "can every renderer downstream draw
// it" — because a value that gets through here and then throws does not fail
// once, it takes a panel out for good.
//
// Two holes were open for exactly that long:
//
//   `name` was optional, and waypoints.ts escapes names with s.replace(), which
//   throws on undefined *inside renderList* — so one nameless pin in a restored
//   backup meant the Marks panel never opened again, in that session or any
//   after it, and GPX export was dead too.
//
//   Coordinates were only checked for finiteness, so lat: 200 was accepted.
//   maplibregl.LngLat throws above 90, which kills refreshMarkers and takes the
//   whole waypoints module down at startup.
//
// Both are what isStr and isLatLng in valid.ts exist for; gpx.ts was already
// range-checking its input, so the importer was stricter than the restorer.
function isWaypoint(w: any): w is Waypoint {
  return (
    w && isId(w.id) &&
    isStr(w.name) &&
    isLatLng(w.lat, w.lng) &&
    isOptStr(w.note)
  );
}
function isTrack(t: any): t is Track {
  return (
    t && isId(t.id) &&
    isStr(t.name) &&
    Array.isArray(t.pts) &&
    t.pts.every((p: any) => Array.isArray(p) && isLatLng(p[1], p[0]))
  );
}

// Set when the stored marks could not be read or parsed. While true we must
// never write: "I couldn't read your marks" and "you have no marks" are the
// same value in memory, and saving that emptiness destroys the real file.
let readFailed = false;

// The last Marks successfully read or written — the shared in-memory truth.
//
// One file, several owners: the Marks panel owns waypoints and tracks, the Plan
// panel owns plans. Each knows only its own slice, so any of them writing a
// whole Marks erases the others' work. That is not hypothetical — the first
// version of this did exactly that, and every pin you dropped silently deleted
// your bug-out plan. Modules write through updateMarks and never touch the
// other slices.
let current: Marks = empty();

/** The marks as last read or written. */
export function currentMarks(): Marks {
  return current;
}

/** Did the last load fail? Callers should not present an empty list as fact. */
export function marksUnreadable(): boolean {
  return readFailed;
}

export async function loadMarks(): Promise<Marks> {
  if (!hasTauri()) return (current = readLocalStorage());

  let fromFile = empty();
  try {
    const raw = await invoke<string>("read_marks");
    if (raw.trim()) fromFile = normalize(JSON.parse(raw));
    readFailed = false;
  } catch (e) {
    // Either the backend refused (a real IO error, not a missing file) or the
    // JSON is corrupt. Both mean "unknown", not "empty".
    readFailed = true;
    console.error("[griddown] marks unreadable", e);
    return empty();
  }

  // One-time migration: if the file is empty but localStorage still holds the
  // old data, adopt it and write it through to the durable store.
  //
  // `isEmpty` covers plans too, and must: someone whose only data is a saved
  // plan has a file that is not empty, and adopting localStorage over it would
  // save a Marks with `plans: []` straight on top of the plan.
  if (isEmpty(fromFile)) {
    const legacy = readLocalStorage();
    if (!isEmpty(legacy)) {
      await saveMarks(legacy);
      return legacy;
    }
  }
  return (current = fromFile);
}

/**
 * Save a patch over whatever else is stored.
 *
 * The only write path modules should use. Passing `{ waypoints }` keeps the
 * plans exactly as they were, and vice versa — see `current` above for why that
 * matters.
 */
export async function updateMarks(patch: Partial<Marks>): Promise<void> {
  await saveMarks({ ...current, ...patch });
}

export async function saveMarks(m: Marks): Promise<void> {
  // Refuse to write over marks we failed to read. Otherwise the first UI action
  // after a failed load persists an empty set on top of the user's real data —
  // and the .bak gets overwritten with it on the write after that.
  if (readFailed) {
    throw new Error(
      "Not saving: your existing marks couldn't be read, and saving now would overwrite them. Restart the app; if it persists, restore from a backup."
    );
  }
  // Mirror to localStorage too: harmless, and it keeps a second copy around on
  // the off chance the app data dir is lost.
  writeLocalStorage(m);
  current = m;
  if (!hasTauri()) return;
  try {
    await invoke("write_marks", { json: JSON.stringify(m) });
  } catch (e) {
    console.error("Failed to save marks", e);
    throw e;
  }
}
