import { invoke } from "@tauri-apps/api/core";

// Durable storage for the user's own data — waypoints and recorded tracks.
//
// These are the only things in the app that can't be regenerated: a map pack can
// be re-downloaded, a pin you dropped in the field can't. They used to live in
// localStorage, which in a Tauri app is a webview cache directory that a
// reinstall or webview update can silently wipe. They now live in marks.json in
// the app data dir, written atomically on the Rust side.
//
// localStorage is still the fallback when there's no Tauri backend (plain
// `vite dev` in a browser), and is read once to migrate existing data over.

export interface Waypoint {
  id: string;
  name: string;
  lat: number;
  lng: number;
  note?: string;
  t: number;
}
export type Pt = [number, number, number?]; // lng, lat, ele?
export interface Track {
  id: string;
  name: string;
  pts: Pt[];
  t: number;
}
export interface Marks {
  waypoints: Waypoint[];
  tracks: Track[];
}

const WP_KEY = "griddown_waypoints";
const TR_KEY = "griddown_tracks";

const empty = (): Marks => ({ waypoints: [], tracks: [] });

function hasTauri(): boolean {
  return typeof (window as any).__TAURI_INTERNALS__ !== "undefined";
}

function readLocalStorage(): Marks {
  const parse = <T>(key: string): T[] => {
    try {
      const v = JSON.parse(localStorage.getItem(key) || "[]");
      return Array.isArray(v) ? v : [];
    } catch {
      return [];
    }
  };
  return { waypoints: parse<Waypoint>(WP_KEY), tracks: parse<Track>(TR_KEY) };
}

function writeLocalStorage(m: Marks) {
  try {
    localStorage.setItem(WP_KEY, JSON.stringify(m.waypoints));
    localStorage.setItem(TR_KEY, JSON.stringify(m.tracks));
  } catch {
    /* quota or disabled storage — the file is the real store anyway */
  }
}

/** Coerce anything we read back into a well-formed Marks. */
export function normalize(v: any): Marks {
  const m = empty();
  if (v && typeof v === "object") {
    if (Array.isArray(v.waypoints)) m.waypoints = v.waypoints.filter(isWaypoint);
    if (Array.isArray(v.tracks)) m.tracks = v.tracks.filter(isTrack);
  }
  return m;
}

// Ids are generated by us (rid()), but they also arrive from restored backups
// and GPX imports, which are attacker-supplied files. They end up in `data-*`
// attributes, so an id containing a quote could break out of the attribute.
// Constrain them here as well as escaping on output — a restore should not be
// able to smuggle markup into the Marks panel.
const ID_RE = /^[A-Za-z0-9_-]{1,64}$/;

// Types are checked as well as ids. A restored backup is a file someone else
// may have written, and the renderers assume these are strings and numbers —
// a numeric `name` reaches `.replace()` and throws, which takes out the Marks
// panel entirely, and a malformed `pts` produces NaN coordinates that make
// fitBounds throw. Rejecting the entry is better than a panel that won't open.
function isWaypoint(w: any): w is Waypoint {
  return (
    w && typeof w.id === "string" && ID_RE.test(w.id) &&
    Number.isFinite(w.lat) && Number.isFinite(w.lng) &&
    (w.name === undefined || typeof w.name === "string") &&
    (w.note === undefined || typeof w.note === "string")
  );
}
function isTrack(t: any): t is Track {
  return (
    t && typeof t.id === "string" && ID_RE.test(t.id) &&
    (t.name === undefined || typeof t.name === "string") &&
    Array.isArray(t.pts) &&
    t.pts.every(
      (p: any) => Array.isArray(p) && Number.isFinite(p[0]) && Number.isFinite(p[1])
    )
  );
}

// Set when the stored marks could not be read or parsed. While true we must
// never write: "I couldn't read your marks" and "you have no marks" are the
// same value in memory, and saving that emptiness destroys the real file.
let readFailed = false;

/** Did the last load fail? Callers should not present an empty list as fact. */
export function marksUnreadable(): boolean {
  return readFailed;
}

export async function loadMarks(): Promise<Marks> {
  if (!hasTauri()) return readLocalStorage();

  let fromFile = empty();
  try {
    const raw = await invoke<string>("read_marks");
    if (raw.trim()) fromFile = normalize(JSON.parse(raw));
    readFailed = false;
  } catch (e) {
    // Either the backend refused (a real IO error, not a missing file) or the
    // JSON is corrupt. Both mean "unknown", not "empty".
    readFailed = true;
    console.error("[griddown] marks unreadable", e);
    return empty();
  }

  // One-time migration: if the file is empty but localStorage still holds the
  // old data, adopt it and write it through to the durable store.
  if (!fromFile.waypoints.length && !fromFile.tracks.length) {
    const legacy = readLocalStorage();
    if (legacy.waypoints.length || legacy.tracks.length) {
      await saveMarks(legacy);
      return legacy;
    }
  }
  return fromFile;
}

export async function saveMarks(m: Marks): Promise<void> {
  // Refuse to write over marks we failed to read. Otherwise the first UI action
  // after a failed load persists an empty set on top of the user's real data —
  // and the .bak gets overwritten with it on the write after that.
  if (readFailed) {
    throw new Error(
      "Not saving: your existing marks couldn't be read, and saving now would overwrite them. Restart the app; if it persists, restore from a backup."
    );
  }
  // Mirror to localStorage too: harmless, and it keeps a second copy around on
  // the off chance the app data dir is lost.
  writeLocalStorage(m);
  if (!hasTauri()) return;
  try {
    await invoke("write_marks", { json: JSON.stringify(m) });
  } catch (e) {
    console.error("Failed to save marks", e);
    throw e;
  }
}
